version: "3.2"

services:
  web:
    build: ./
    volumes:
      - ./:/usr/src/app/  # /app
    ports:
      - 5000:5000
    command: "gunicorn -b 0.0.0.0:5000 index:server \
              --capture-output --log-level debug"
